name: Build and deploy Node.js app to Azure Web App - devspire

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present
          npm prune --production  # Remove devDependencies to reduce package size

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./dist  # or ./build — adjust based on your output folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6487B4D15DF04BA3818B2E7CAFA1B0EF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A31231888114427DB2F66BF868A9B0CD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1AA3AAC09D8B4FB0BBC8D97D662797D1 }}

      - name: Deploy to Azure Web App (dev slot)
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'devspire'
          slot-name: 'dev'  # uses dev deployment slot
          package: .
          deployment-method: runFromPackage
